"""Offline credential cracker — real NT-hash + Kerberos RC4 roast cracking.

The Kerberos fixtures below were generated by impacket's RC4-HMAC encryption
(an independent implementation) for password ``Summer2026!`` — see the E3 build
notes — so these tests validate our decryption against genuine roast blobs while
keeping the suite free of the impacket dependency (rule §2: zero external services).
"""

from __future__ import annotations

from attack_engine.credentials.cracker import HashCracker, nt_hash

# password = "Summer2026!"
_NT = "41aed72cec76816423703d8e545eea31"
_TGS = (
    "$krb5tgs$23$*svc_sql*CORP.LOCAL*MSSQL/db*$"
    "5bf73a77ffb2392433271d4b7c2fc8d1$"
    "364a207fe91c05e8eaeaf5d775c6bdf726f9edd61276cd52b62d8fcdcab9"
)
_ASREP = (
    "$krb5asrep$23$alice@CORP.LOCAL:"
    "d4fd6f63511e236f51481cce3a1f3c7e$"
    "1a93705fece177750d114ba2fa7e78fddd691c90f53f53796fa8fd271333"
)
_WORDLIST = ["Winter2025", "Password1", "Summer2026!", "admin"]


def test_nt_hash_helper_matches_known_value() -> None:
    assert nt_hash("Summer2026!").hex() == _NT


def test_crack_nt_recovers_plaintext() -> None:
    result = HashCracker().crack_nt(_NT, _WORDLIST)
    assert result.cracked
    assert result.plaintext == "Summer2026!"
    assert result.tried == 3  # stops at the match


def test_crack_nt_is_case_insensitive_on_hex() -> None:
    assert HashCracker().crack_nt(_NT.upper(), _WORDLIST).cracked


def test_crack_nt_miss_reports_full_effort() -> None:
    result = HashCracker().crack_nt(_NT, ["nope", "wrong", "bad"])
    assert not result.cracked and result.plaintext is None
    assert result.tried == 3


def test_crack_kerberoast_tgs() -> None:
    result = HashCracker().crack_kerberos(_TGS, _WORDLIST)
    assert result.cracked and result.plaintext == "Summer2026!"


def test_crack_asrep_roast() -> None:
    result = HashCracker().crack_kerberos(_ASREP, _WORDLIST)
    assert result.cracked and result.plaintext == "Summer2026!"


def test_crack_kerberos_wrong_password_fails() -> None:
    result = HashCracker().crack_kerberos(_TGS, ["nope", "wrong"])
    assert not result.cracked


def test_crack_kerberos_unrecognized_format() -> None:
    result = HashCracker().crack_kerberos("not-a-roast-blob", _WORDLIST)
    assert not result.cracked and result.tried == 0
